version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: salamat
      POSTGRES_PASSWORD: QWE123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
